[package]
name = "generator-pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.30", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
regex = "1.11.1"